### ISSUE TITLE
Replace terms blacklist & whitelist in configuration

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1154]
@simonihmig and myself had a quick chat on discord about the configuration options `blacklist` and `whitelist`. We decided to rename them. Our feature is similar to the one currently called `blacklist` and `whitelist` in Ember itself. [RFC 639](https://github.com/emberjs/rfcs/pull/639) proposed to rename them. The RFC is currently in final comment period. We decided to follow the chosen naming in that RFC as soon as it's merged. The old names should be deprecated but not removed yet.

**Comment by sandstrom** [comment]
I'll leave this here for posterity:

> The English dramatist Philip Massinger used the phrase "black list" in his 1639 tragedy The Unnatural Combat.
> 
> After the restoration of the English monarchy brought Charles II of England to the throne in 1660, a list of regicides named those to be punished for the execution of his father. The state papers of Charles II say "If any innocent soul be found in this black list, let him not be offended at me, but consider whether some mistaken principle or interest may not have misled him to vote". In a 1676 history of the events leading up to the Restoration, James Heath (a supporter of Charles II) alleged that Parliament had passed an Act requiring the sale of estates, "And into this black list the Earl of Derby was now put, and other unfortunate Royalists".
> 
> Edward Gibbon wrote in The History of the Decline and Fall of the Roman Empire (1776) of Andronicus that "His memory was stored with a black list of the enemies and rivals, who had traduced his merit, opposed his greatness, or insulted his misfortunes".
> 
> — https://en.wikipedia.org/wiki/Blacklisting#Origins_of_the_term
