### ISSUE TITLE
Enable tests for `@onClick` action of `<BsButton>` throws again

### ISSUE THREAD

**Issue by simonihmig** [ember-bootstrap/ember-bootstrap#1615]
#1581 added tests using custom assertion `assert.rejectsErrorNotHandledByEmberOnError` to test cases of rejected promises. These started to make [CI fail](https://github.com/kaliber5/ember-bootstrap/actions/runs/1244130788) for jobs not using our locked dependencies. Probably some updates to qunit changed some behaviour here!?

@jelhan

**Comment by jelhan** [comment]
See #1616 for tests, which are skipped due to issues with testing Ember code, which throws.
