### ISSUE TITLE
[QUESTION] How to write sub items on bootstrap navbar using these components? 

### ISSUE THREAD

**Issue by villander** [ember-bootstrap/ember-bootstrap#1679]
Looking at the documentation we don't have a way to write sub-items on the navbar, is it right? 

https://www.ember-bootstrap.com/api/classes/Components.Navbar.html

**Comment by jelhan** [comment]
I'm not sure what you mean by "sub-items" to be honest. Would be great if you could elaborate a little bit. I often find pseudo-code (e.g. HTML markup you are trying to achieve) and/or references to official Bootstrap documentation very helpful.

**Comment by villander** [comment]
```js
<BsNavbar as |navbar|>
  <div class="navbar-header">
    <navbar.toggle />
    <a class="navbar-brand" href="#">Brand</a>
  </div>
  <navbar.content>
    <navbar.nav as |nav|>
      <nav.item as |Item|>
         Settings
      <Item.submenu as |sub|>
      <sub.item>
        <LinkTo @route="product-settings">Product Settings</LinkTo>
      </sub.item>
    </Item.submenu>
        
      </nav.item>
      <nav.item>
        <nav.linkTo @route="navbars">Navbars</nav.linkTo>
      </nav.item>
    </navbar.nav>
  </navbar.content>
</BsNavbar>
```

I hope it's clear now @jelhan

**Comment by simonihmig** [comment]
@villander you mean an item is a dropdown, features sub items in its menu? For that there is an example here: https://www.ember-bootstrap.com/components/navbars
