### ISSUE TITLE
Error "Backdrop element should be in DOM" when using the `BsModal` component.

### ISSUE THREAD

**Issue by BnitoBzh** [ember-bootstrap/ember-bootstrap#1786]
After upgrading to version 5.0.0, and 5.1.0 i got the error `Backdrop element should be in DOM`when using the `BsModal` component.
After a few tries with the `yarn upgrade-interactive` command and the `resolutions` option on `package.json` file.
I noticed that the problem comes with version 4.1.0 of the `ember-ref-bucket` addon.

For now, i don't know why .. probably due to this commit https://github.com/lifeart/ember-ref-bucket/commit/8edeb49fba36888a1efb622ec4050f0bcdf8ef77

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^5.0.0 -> 5.1.0
ember-cli: ~3.28.4 -> 3.28.5
bootstrap: ^4.0.0 -> 4.6.1
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
insertEmberWormholeElementToDom: false
```

**Comment by simonihmig** [comment]
For the record, as this has been discussed on Discord: I think the problem comes from having different versions of `ember-modifier` in your lockfile:

> No, there is no fix in the works, as there is likely nothing to be fixed on ember-bootstrap's side. As mentioned earlier,  I assume there might be an issue with different versions of ember-modifier. So either all addons have to be updated to use the latest, or pinned to at least use the same version.  There should be no different versions of the same addon be used in the same app.

I'll keep this open for visibility, but AFAICT there is nothing to fix here.

**Comment by naomi-nori** [comment]
The multiple versions of `ember-modifier` was the ticket for me as well. Though ultimately it was `ember-style-modifier` that was the primary culprit, it, prior to updating, including `ember-modifier@2.*.*`. 

With it working at this point it still looks like I have multiple versions but they're all of the same major version.
