### ISSUE TITLE
Yield form's model from <BsForm>

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1806]
In some cases you may need to access the model used for `<BsForm>`. E.g. if you want to show a value of a form's property or getter in the form.

This could be currently done by using the same object as passed to `<BsForm>` as model:

```hbs
<BsForm @model={{this.someObject}} as |form|>
  <form.element @property="foo" />
  Current value of <code>foo</code> is {{this.someObject.foo}}
</BsForm>
```

Wondering if we should yield the form's model from `<BsForm>` as `form.model` to make this more readable:

```hbs
<BsForm @model={{this.someObject}} as |form|>
  <form.element @property="foo" />
  Current value of <code>foo</code> is {{form.model.foo}}
</BsForm>
```

This would also ease migration to decoupling form's model from default values. I proposed this in #1551 last year but haven't had the time to follow up. Providing access to form's model in `<BsForm>` block even if it is constructed and managed internally would be a first step towards that direction.

**Comment by lindyhopchris** [comment]
This would be really useful IMHO, as I currently have to do this:

```hbs
{{#let (changeset @organiser this.validator) as |model|}}
  <BsForm
    @model={{model}}
    @onBefore={{this.handleBefore}}
    @onSubmit={{@onSubmit}}
    as |Form|
  >
```

So that I can access the changeset _within_ the form. It would be a lot easier if I could just do:

```hbs
  <BsForm
    @model={{changeset @organiser this.validator}}
    @onBefore={{this.handleBefore}}
    @onSubmit={{@onSubmit}}
    as |Form|
  >
```

and then access the changeset as `Form.model`.

**Comment by jelhan** [comment]
Adding help wanted label assuming that @simonihmig does not have any concerns.

I only have very limited time for open source these days. If anyone needs this soon, providing a pull request will help to speed it up.

**Comment by lindyhopchris** [comment]
Was thinking this might be an alternative syntax:

```hbs
  <BsForm
    @model={{changeset @organiser this.validator}}
    @onBefore={{this.handleBefore}}
    @onSubmit={{@onSubmit}}
    as |Form model|
  >
```

If we don't consider the model as a property of the form?

**Comment by bvedad** [comment]
I will take this issue.

**Comment by jelhan** [comment]
> Was thinking this might be an alternative syntax:
> 
> ```
>   <BsForm
>     @model={{changeset @organiser this.validator}}
>     @onBefore={{this.handleBefore}}
>     @onSubmit={{@onSubmit}}
>     as |Form model|
>   >
> ```
> 
> If we don't consider the model as a property of the form?

I prefer the other form to be honest. Mainly because yielding multiple values is not that common in Ember ecosystem. But not highly opinionated on it.

**Comment by lindyhopchris** [comment]
@jelhan I'm not highly opinionated about it either, so probably best to just go with your original suggestion!
