### ISSUE TITLE
The `element` helper polyfill encountered an unexpected error

### ISSUE THREAD

**Issue by khaled-s** [ember-bootstrap/ember-bootstrap#1807]
`Assertion Failed: The `element` helper polyfill encountered an unexpected error`

this error is showing up when using`BsDropdown`
it was working until I upgraded to the latest version of `ember-bootstrap`
going back to `5.0.0-beta.2` fixes the problem

```
Npm packages:
ember-bootstrap: ^5.1.1 -> 5.1.1
ember-cli: 3.28.4 -> 3.28.4
bootstrap: ^5.2.0 -> 5.2.0
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 5
importBootstrapCSS: false

```

**Comment by dagroe** [comment]
Had the same problem. Adding a resolution for `"ember-element-helper": "0.6.1"` solved it for me.

**Comment by jelhan** [comment]
Please have a look at this upstream issue: https://github.com/tildeio/ember-element-helper/issues/92
