### ISSUE TITLE
Modal invisible after opening it, as the show class is missing

### ISSUE THREAD

**Issue by toovy** [ember-bootstrap/ember-bootstrap#1818]
Hi,

I'm experiencing a weird issue from time to time, that can not be solved by reloading, but only by opening the app in a new tab. I'm on Mac 12.6 with Chrome 105 with Ember 4.4.2. 

After clicking a button that usually reveals the modal, it is not displayed (i.e. invisible), but still it is rendered in the DOM, making the ember-app unusable, because the invisible modal still overlays all other elements.

There are no errors in the javascript console. What I can see from the DOM is that still receives the class `modal-open `, the `ember-bootstrap-wormhole` is there with a `div` with classes `modal fade  d-block modal-hide-footer`, and that looks correct, only the `show` class is missing.

The strange thing is, that reloading the tab does not solve the issue, but opening the same URL in a new tab does.

This is the code:

```
<BsModalSimple
  @open={{this.showItemFormDialog}}
  @title={{t 'components.deliveries.items.add'}}
  @size='lg'
  @onHidden={{fn (mut this.showItemFormDialog) false}}
  class='modal-hide-footer'
>
  ...
</BsModalSimple>
```

Pretty straight forward...

Any idea what might be. the issue?

**Update:**

![image](https://user-images.githubusercontent.com/350002/194282596-a06e37d3-6919-42e1-b7dc-8eb6c06a53e0.png)

I can see that in the sessions, where the modal is not opening, the `open` method in `addon/components/bs-modal.js` just drops out at `await this.showBackdrop();`, i.e. there seems to be an unresolved promise...

**Update 2:**

I could track it down to the transitionEnd fn, that internally calls `resolve()` in line 32, but somehow the process is just not continued, i.e. I have no idea what is going on, might be an Chrome issue?

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^5.1.1 -> 5.1.1
ember-cli: ~4.4.0 -> 4.4.1
bootstrap: ^5.2.0-beta1 -> 5.2.1
bootstrap-sass: n/a
ember-cli-sass: ^11.0.1 -> 11.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 5
importBootstrapCSS: false
```

**Comment by jelhan** [comment]
I'm sorry for not coming back to this bug report earlier. Are you still facing the issue or did you were able to resolve it in the meantime?

If you are still struggling with it, a reproduction would be helpful.

**Comment by toovy** [comment]
@jelhan We could not solve it. The issue does only occur when the developer console is open in chrome and when you had breakpoints, and live-reload(s) afterwards. This being said I assume this is a chrome issue, while being kind of annoying, at least this is not an issue when the app is used in prod. 🤷

**Comment by jelhan** [comment]
If it is only reproducible if having a breakpoint in debugger, it could be a timing issue as well. But not sure if we want to invest debugging something, which could be only reproduced if having breakpoints set in developer tools.

Is this caused by setting breakpoints in your application code? Or only if you are setting breakpoints in Ember Bootstrap's code?

**Comment by toovy** [comment]
It's when I debug my applications code, not necessarily when I debug Ember Bootstraps code. I guess it is not worth investing more time to find the issue. I still guess that this might be a chrome issue as the transitionEnd is just not fired any more.
