### ISSUE TITLE
Doesn't work in embroider. 

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-bootstrap/ember-bootstrap#1831]
`ember-focus-trap` is not imported in a way that embroider understands. In embroider you get a `module not found` error.

```
Module not found: 
Error: Can't resolve 'ember-focus-trap/modifiers/focus-trap.js' in 
'$TMPDIR/embroider/e41e4f/modifiers/focus-trap.js'
```

**Comment by ef4** [comment]
https://github.com/ember-bootstrap/ember-bootstrap/actions/runs/3201363854/jobs/5229278773

**Comment by BryanCrotaz** [comment]
I reproduced it like this:
1. ember new my-app, cd my-app
2. ember install @html-next/vertical-collection
3. move to using embroider
4. yarn add ember-bootstrap
5. ember s
module not found: ember-focus-trap

**Comment by ef4** [comment]
I confirmed that this is definitely the same as https://github.com/embroider-build/embroider/issues/1175, so this issue on ember-bootstrap can probably be closed. The addon isn't doing anything wrong, it's an embroider bug.
