### ISSUE TITLE
Error when BsTooltip is used when ember-modifier is installed

### ISSUE THREAD

**Issue by trippetoe** [ember-bootstrap/ember-bootstrap#1869]
When I add `ember-modifier` to my application, my `BsTooltip`s do not display correctly. The tooltip contents are placed in the upper-left corner and the screen flashes (i guess quickly adding/removing the tooltip contents). This behavior is repeatable. My tests were done using the current version of `ember-modifier` v4.0.0. `ember-bootstrap` details are below.

1.  Create a new ember app (i used the quick start app from Ember docs)
2. Add ember-bootstrap *(after downgrading ember-auto-import to v2.5.0)*
3. Add a simple BsForm (i had a single input and submit button)
4. Add a BsTooltip to any element in the component or template _(run the app to verify everything is working as expected)_
5. Add ember-modifier `ember install ember-modifier`
6. Generate a modifier `ember g modifier autofocus`
7. Add the modifier `{{autofocus}}` to the text input markup
8. `ember s`
9. hover over the element with the tooltip. tooltip will display in upper left corner of app *(see first screen cap below)*
10. stop the ember server and remove ember-modifier `npm uninstall ember-modifier`
11. `ember s`
12. hover over the element with the tooltip. tooltip will display as expected to the right of the element *(see second screen cap below)*

With `ember-modifier` installed
![image](https://user-images.githubusercontent.com/22507276/219511453-a719c04e-0389-43d7-880f-73b487df3809.png)

Without `ember-modifier` installed
![image](https://user-images.githubusercontent.com/22507276/219511583-166059cd-3375-4f34-aaed-82b8b8658c82.png)

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^5.1.1 -> 5.1.1
ember-cli: ~4.7.0 -> 4.7.0
bootstrap: ^5.2.3 -> 5.2.3
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 5
importBootstrapCSS: true
```

**Comment by jelhan** [comment]
Ember Modifier v4 is not supported by Ember Bootstrap 5.x. It is supported by 6.x, for which there is a prerelease currently: v6.0.0-1. Would be great if you could test with that release.

**Comment by trippetoe** [comment]
I updated to ember-bootstrap v6.0.0-1, and the tooltips behaved as expected. I changed the combinations of placement and triggerEvents and again all behaved as expected.

Recommendations for incorporating 6.0.0-1 into our app? when is the official release scheduled? The app is to support us internally with no access from outside the firewall. So, its a 'Production' app but not mission-critical.

**Comment by jelhan** [comment]
Test coverage is the same as with v5. No known bugs . Expected changes before releasing stable version are documented here: #1840. None of them is expected to require noticeable refactoring for consuming apps. In my opinion it should be safe to use.

As an alternative you could stay on ember-modifier v3 for now.
