### ISSUE TITLE
Installing ember-power-select breaks BsPopover

### ISSUE THREAD

**Issue by lolmaus** [ember-bootstrap/ember-bootstrap#1939]
Hi!

As [Arno Schneider](https://stackoverflow.com/users/13126614/arno-schneider) reported in a [StackOverflow question](https://stackoverflow.com/q/76651308/901944), BsPopover becomes broken when you install `ember-power-select`.

Here's a greenfield Ember 4.12.1 app with `ember-bootstrap` and BsPopover:

![image](https://github.com/ember-bootstrap/ember-bootstrap/assets/200884/dcf7ff49-754a-485b-90e8-ef5bc941ee2b)

![image](https://github.com/ember-bootstrap/ember-bootstrap/assets/200884/8ca6bd96-8738-4728-942e-4125108febbf)

As you can see, the data attribute and the style attribute are applied.

***

But when you do `ember i ember-power-select` and restart the dev server, here's what you get:

![image](https://github.com/ember-bootstrap/ember-bootstrap/assets/200884/17143a07-4589-4f9a-8eb2-55dd3879a9e2)

![image](https://github.com/ember-bootstrap/ember-bootstrap/assets/200884/11280367-fc91-49d7-a21a-30ed5d9ec459)

As you can see, the data attribute and the style attribute are not applied, and the popover is rendered in the flow, breaking markup.

---

Output from `ember bootstrap:info`:

```
❯ ember bootstrap:info
Npm packages:
ember-bootstrap: ^5.1.1 -> 5.1.1
ember-cli: ~4.12.1 -> 4.12.1
bootstrap: ^5.3.0 -> 5.3.0
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 5
importBootstrapCSS: true
```

**Comment by lolmaus** [comment]
Here's a demo app:
https://github.com/lolmaus/ember-app-bootstrap-power-select

See these two commits:

* https://github.com/lolmaus/ember-app-bootstrap-power-select/commit/3b505923dd56246d3d193298d5799197dc6b44ad — installing `ember-bootstrap`, creating `index.hbs` and copy-pasting the BsPopover example. It works!
* https://github.com/lolmaus/ember-app-bootstrap-power-select/commit/afe881ab106291b73a4070ea7d36c98f4725c6db — simply installing `ember-power-select`, no changes to the code. It's broken now!

The implementation of `BsPopover` turned out to be a bit more complex than I can handle with a quick glance.

I suspected a dependency version clash, but could not find one.

**Comment by simonihmig** [comment]
> I suspected a dependency version clash, but could not find one.

Yeah, haven't investigated, but I would guess likely due to some different versions of ember-modifier. ember-popper-modifier v2 seems to depend on ember-modifier v3, while the rest is on v4. Updating e-b to the latest 6.0.0-2, which uses  ember-popper-modifier v3, and ensuring no other addon depends on v3 might already fix this.

**Comment by arnoschneid** [comment]
I can acknowledge that with ember-bootstra version 6.0.0-2 the version 3 of ember-popper-modifier is used and the error is solved. Thanks!
