### ISSUE TITLE
Ember 5.x Compatibility

### ISSUE THREAD

**Issue by mdconaway** [ember-bootstrap/ember-bootstrap#1949]
Hi, and thanks for this great addon!

It looks like ember-bootstrap works with Ember 5.x, but fails to install without the `--legacy-peer-deps` flag due to a package.json dependency declared here: https://github.com/ember-bootstrap/ember-bootstrap/blob/master/package.json#L62

Because of this dependency, the following error message is thrown on `ember install`:

---

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ember-element-helper@0.6.1
npm WARN Found: ember-source@5.2.0
npm WARN node_modules/ember-source
npm WARN   dev ember-source@"~5.2.0" from the root project
npm WARN   11 more (@ember/render-modifiers, @ember/test-helpers, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer ember-source@"^3.8 || 4" from ember-element-helper@0.6.1
npm WARN node_modules/ember-element-helper
npm WARN   ember-element-helper@"^0.6.0" from ember-bootstrap@5.1.1
npm WARN   node_modules/ember-bootstrap
npm WARN 
npm WARN Conflicting peer dependency: ember-source@4.12.3
npm WARN node_modules/ember-source
npm WARN   peer ember-source@"^3.8 || 4" from ember-element-helper@0.6.1
npm WARN   node_modules/ember-element-helper
npm WARN     ember-element-helper@"^0.6.0" from ember-bootstrap@5.1.1
npm WARN     node_modules/ember-bootstrap
```

I believe upgrading to the latest version of `ember-element-helper` could fix the issue.

I can submit a pull request if needed, just let me know!

**Comment by jelhan** [comment]
Thanks a lot for reporting. A PR which widens the version range for `ember-element-helper` to allow `^0.6.0 || ^0.7.0 || ^0.8.0` is very welcome.

**Comment by SaumyaBhushan** [comment]
Hey @jelhan @mdconaway Can I work on this issue ?

**Comment by mdconaway** [comment]
Sure thing @SaumyaBhushan , all yours !
