### ISSUE TITLE
Migrate to a modern package manager

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1979]
This project is still using yarn v1. We should migrate to a recent version of NPM, Yarn or PNPM.

This includes:

* Updating the GitHub Actions to use the other package manager
* Regenerating lock file with that new package manager
* Adjusting RenovateBot configuration
* Updating contribution docs

It should be implemented both for the addon as well as the docs app.

**Comment by simonihmig** [comment]
I used pnpm in the more recent projects, would probably suggest that. It's much better at getting peer deps right. Yarn PnP might also be able to do this, however I believe we'll run into issues with the ember ecosystem expecting traditional node_modules on disk...
