### ISSUE TITLE
Refactor to Glimmer components

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#2012]
The addon is still using `@ember/component` for many components. We should refactor to `@glimmer/component`.

Any support is highly appreciated. Let me know if you can pick up one component (or more). I recommend doing only one or a few closely related components in the same PR to ease review and speed up getting it in.

I hope that it does not require any breaking changes as we have prepared for that refactoring long ago.

List of components, which are still using `@ember/component`:

- [x] `<BsCarousel>` (#2038)
- [x] `<BsCarousel::Slide>` (#2038)
- [x] `<BsDropdown>` (#2031)
- [x] `<BsDropdown::Menu>` (#2031)
- [x] `<BsDropdown::Menu::Divider>` (#2031)
- [x] `<BsDropdown::Menu::Item>` (#2031)
- [x] `<BsDropdown::Toggle>` (#2031)
- [x] `<BsLinkTo>` (#2043)
- [x] `<BsNav>` (#2020)
- [x] `<BsNav::Item>` (#2043)
- [x] `<BsNavbar>` (#2025)
- [x] `<BsNavbar::Content>` (#2025)
- [x] `<BsNavbar::Toggle>` (#2025)
- [x] `<BsProgress>` (#2030)
- [x] `<BsProgress::Bar>` (#2030)
- [x] `<BsTab>` (#2034)
- [x] `<BsTab::Pane>` (#2034)

**Comment by SanderKnauff** [comment]
For the `BsNav::Item` and `BsLinkTo` I ran into an issue with the way parent/child lookups are being done.

In most of the new code, we pass through `registerChild/unregisterChild` functions from the parent to the child.
The old code relies on Ember for finding the nearest component of a type using the `nearestOfType` function.

Due to the way Bs::Nav yields children, it is not possible to have it exactly the same way in glimmer. Namely, the following situation will cause issues:
```hbs
<BsNav as |nav|>
  <nav.item>
    <nav.link-to @route='application'>Dummy</nav.link-to>
  </nav.item>
</BsNav>
```

We have no way of telling the `nav.link-to` that it should register itself as a child of `nav.item`.

What should we do in this situation?

**Comment by jelhan** [comment]
Thanks a lot for investigating.

I think the root cause is that the `<BsLinkTo>` component is yielded from `<BsNav>`. But it should be yielded from `<BsNav::Item>` as it is expected to be used as a child of that one.

Changing which component yields `<BsLinkTo>` would be a breaking change. And would require touching all usages of it in all consuming apps. I would like to prevent that for now.

Would it be possible to register the `<BsLinkTo>` instances in `<BsNav>` and pass them as an argument to `<BsNav::Item>` for now?

**Comment by jelhan** [comment]
Got it. Moving to `<BsNav>` is not possible.

I wonder if it is needed anymore at all. It seems to be used to set `active` and `disabled` CSS classes on `<li class="nav-item">`.

I cannot find having `active` or `disabled` CSS class on `<li class="nav-item">` for Bootstrap 4 or 5 in Bootstrap's documentation. I can only find it in Bootstrap 3. In Bootstrap 4 and 5 the `active` and `disabled` CSS classes are on the `<a>` element, which is rendered by `<BsLinkTo>` itself.

Unless I missed something the code seems to be a leftover from Bootstrap 3 support, which we missed to remove. Would be great if you could double check as well.

Assuming I haven't missed something, I would recommend doing 2 PRs:

1. Removing `active` and `disabled` CSS classes from `<li class="nav-item">` and all code related to it.
2. Refactoring `<BsNav::Item>` to Glimmer component, which should be unblocked after we landed the cleanup in first step.

I prefer two PRs to highlight the markup change more prominently in changelog. I don't think it's a breaking change. I would consider that HTML private implementation detail and not matching markup from Bootstrap docs as a bug. But clearly documenting the change might be good anyways.

**Comment by SanderKnauff** [comment]
> Got it. Moving to `<BsNav>` is not possible.
> 
> I wonder if it is needed anymore at all. It seems to be used to set `active` and `disabled` CSS classes on `<li class="nav-item">`.
> 
> I cannot find having `active` or `disabled` CSS class on `<li class="nav-item">` for Bootstrap 4 or 5 in Bootstrap's documentation. I can only find it in Bootstrap 3. In Bootstrap 4 and 5 the `active` and `disabled` CSS classes are on the `<a>` element, which is rendered by `<BsLinkTo>` itself.
> 
> Unless I missed something the code seems to be a leftover from Bootstrap 3 support, which we missed to remove. Would be great if you could double check as well.
> 
> Assuming I haven't missed something, I would recommend doing 2 PRs:
> 
> 1. Removing `active` and `disabled` CSS classes from `<li class="nav-item">` and all code related to it.
> 2. Refactoring `<BsNav::Item>` to Glimmer component, which should be unblocked after we landed the cleanup in first step.
> 
> I prefer two PRs to highlight the markup change more prominently in changelog. I don't think it's a breaking change. I would consider that HTML private implementation detail and not matching markup from Bootstrap docs as a bug. But clearly documenting the change might be good anyways.

Yup, after investigating, I also can only see evidence of it being used for BS3 support. I've created a PR to remove the binding between the two

**Comment by jelhan** [comment]
Thanks a lot to @SanderKnauff for implementing the `@glimmer/component` refactoring.
