### ISSUE TITLE
Run tests on Safari again 

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#2035]
We aren't running our test suite on Safari anymore. BrowserStack tests are disabled since some time. https://github.com/ember-bootstrap/ember-bootstrap/blob/9e7c590cb01370c786f37e1245710d16e65dd98e/.github/workflows/ci.yml#L102-L127

We should run tests on Safari again in CI. Maybe using BrowserStack again. Maybe another service. We may want to have a look why we disabled BrowserStack in the first place.

In case we cannot enable tests on Safari again, we may want to update our compatibility note. Currently it claims:

> Ember Bootstrap works and is fully tested with (...) all modern evergreen browsers (Chrome, Firefox, Safari, Edge)

**Comment by simonihmig** [comment]
> We may want to have a look why we disabled BrowserStack in the first place

IIRC it was just getting too flakey for some reason...

**Comment by SanderKnauff** [comment]
Based on a small test (#2041), it seems we can get away with just using Github CI.

We do seem to be missing automatic testing for Firefox and Edge at the moment.
Personally, I wouldn't bother too much with Edge since it is based on chromium anyway...
