### ISSUE TITLE
Review need of custom CSS 

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#2056]
Ember Bootstrap pushes some custom CSS in the build if using Bootstrap 4.

The custom CSS is located in `vendor/ember-bootstrap` folder. The folder contains CSS files per Bootstrap version. It's injected into the build here: https://github.com/ember-bootstrap/ember-bootstrap/blob/ca3fda9609f875605b6b0283a08b0674c06ad5a0/index.js#L109-L110

The `bs3.css` is not needed anymore. We dropped support for Bootstrap 3 long ago.

We don't inject any custom CSS for Bootstrap 5. `bss5.css` is empty.

For Bootstrap 4 we inject some custom CSS: https://github.com/ember-bootstrap/ember-bootstrap/blob/ca3fda9609f875605b6b0283a08b0674c06ad5a0/vendor/ember-bootstrap/bs4.css#L1-L14

However that custom CSS may not be needed anymore. We should investigate if it's still needed as it 1) increases bundle size of consuming apps a little bit, 2) complicates conversion to a v2 addon (https://github.com/ember-bootstrap/ember-bootstrap/issues/1980#issuecomment-1866113206), and 3) is likely not expected by consumers.

**Comment by jelhan** [comment]
https://github.com/ember-bootstrap/ember-bootstrap/blob/ca3fda9609f875605b6b0283a08b0674c06ad5a0/vendor/ember-bootstrap/bs4.css#L1-L4

This one is likely not needed anymore. The `role="tab"` has been removed in #1844. The selector should not match anything. And no one reported it as a bug so far.

**Comment by SanderKnauff** [comment]
> https://github.com/ember-bootstrap/ember-bootstrap/blob/ca3fda9609f875605b6b0283a08b0674c06ad5a0/vendor/ember-bootstrap/bs4.css#L1-L4
> 
> This one is likely not needed anymore. The `role="tab"` has been removed in #1844. The selector should not match anything. And no one reported it as a bug so far.

I can confirm from testing on an iPad that the bug described does not occur anymore, even without the CSS.

Removing the popover margins however still do influence the positioning a bit
