### ISSUE TITLE
Test app does not rebuild when doing changes to the library

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#2102]
If I'm doing changes in the app, the test app does not rebuild. This is likely broken since the conversion to a monorepo.

**Comment by simonihmig** [comment]
I think this should have fixed it? https://github.com/ember-bootstrap/ember-bootstrap/pull/2100/files#diff-79bd52d36498e1639f62dec1be8cdcc1782f4f489cbf0b5d9bbf73c8da9137ffR26

**Comment by jelhan** [comment]
Yes. Confirmed that it is working on latest master. I guess I hadn't had latest master pulled into my feature branch.
