### ISSUE TITLE
Nested model do only validate 'root' properties

### ISSUE THREAD

**Issue by basz** [ember-bootstrap/ember-bootstrap#219]
see https://github.com/offirgolan/ember-cp-validations/issues/444#issuecomment-276023246

thanks

**Comment by basz** [comment]
Hi, can I aid in moving this forward? It is kind of needed functionality...

**Comment by simonihmig** [comment]
@basz If you come up with an idea how to integrate that functionality in a clean way into the existing system, yes, sure, or cource. Unfortunately I was not able to spend much time on this so far, with other things related to preparing a stable 1.0 release having taken my time, not even speaking of my day to day job... But I do have the desire to provide a good solution to that!

**Comment by basz** [comment]
@simonihmig I do not really have a solution in mind as I do not completely understand how this all works together...

I totally understand if you can't work on this atm. Due to deadlines I will need to work around it then for the time being...

**Comment by basz** [comment]
Hi @simonihmig Did you happen to figure out a way to move this forward?

**Comment by jelhan** [comment]
Closing this issue as stale. Please come back if it is still a problem.
