### ISSUE TITLE
Update documentation to use `@module` and `@submodule` features

### ISSUE THREAD

**Issue by srvance** [ember-bootstrap/ember-bootstrap#227]
We could have a richer documentation hierarchy that would help group the contextual components more naturally if we used the `@module` and `@submodule` directives in yuidoc to group related classes. Imagine `Bootstrap.Accordion.Accordion` and `Bootstrap.Accordion.Item` as an alternative to the current structure.

**Comment by jelhan** [comment]
I think we should not invest more time into existing API docs but rather convert to TypeScript + Glint. The API docs should be provided based on Glint types.
