### ISSUE TITLE
Support tree-shaking `whitelist` and `blacklist` in blueprint

### ISSUE THREAD

**Issue by srvance** [ember-bootstrap/ember-bootstrap#393]
PR #385 added tree-shaking. It would be a nicety to have the blueprint add entries for `whitelist` and/or `blacklist`. This may require an `all` alias value for the whitelist.

**Comment by srvance** [comment]
Depends on srvance/ember-cli-build-config-editor#16

**Comment by jelhan** [comment]
We should encourage treeshaking with Embroider strict mode rather than `include` / `exclude` options. Not saying that we should deprecate them right now. But I also don't feel we should promote them more through the blueprints.
