### ISSUE TITLE
Dropdown in bs-navbar needs active classbinding

### ISSUE THREAD

**Issue by Redsandro** [ember-bootstrap/ember-bootstrap#617]
Some users of my app have indicated they find it confusing that all buttons in the `bs-navbar` have an `active` state, except for the `nav.dropdown` one.

I think this is something that should be implemented upstream, but I'm also curious to know how I can extend the `nav.dropdown` helper manually.

The solution for the helper, if this still works, should be something like [this](https://stackoverflow.com/a/26243440/754174):

```javascript
App.NavItemComponent = Ember.Component.extend({
    tagName: 'li',
    classNameBindings: ['active'],

    active: function(){
        return this.get('childViews').isAny('active');
    }.property('childViews.@each.active')
});
```

.. although I think the `view` thing is outdated.

Is there a way that I can extend this helper in a custom component? How would I use it inside the ember bootstrap helper of navbar?

E.g. the last line here:
```
{{#bs-navbar as |navbar|}}
  {{#navbar.content}}
    {{#navbar.nav as |nav|}}
      {{#nav.dropdown as |dd|}}
```

If it's possible, it will probably be something like:

```
import DropdownComponent from 'ember-bootstrap';
```

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.2.2 -> 1.2.2
ember-cli: ~3.1.4 -> 3.1.4
bootstrap: ^4.1.1 -> 4.1.1
bootstrap-sass: n/a
ember-cli-sass: ^7.1.7 -> 7.1.7
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
> Some users of my app have indicated they find it confusing that all buttons in the bs-navbar have an active state, except for the nav.dropdown one.

To clarify, by buttons you mean actually links (or nav items, i.e. `<li>`s), that get active when the user is on the route they are linking to, right?

> .. although I think the view thing is outdated.

yes, `childViews` is private, and IIRC not reliable to use

> Is there a way that I can extend this helper in a custom component?

Yes, you can extend any component in Ember coming from an addon. Just create a component in the same location and name. here it would be `app/components/bs-dropdown.js`. Inside of it you can import the original to extend from it: `import DropdownComponent from 'ember-bootstrap/components/bs-dropdown';`

**Comment by Redsandro** [comment]
> To clarify, by buttons you mean actually links (or nav items, i.e. <li>s), that get active when the user is on the route they are linking to, right?

Yes. When you have a navbar like so:

```
[link 1] [link 2] [dropdown] [link 5]
                    [link 3]
                    [link 4]
```
.. and link 3 and 4 are hidden inside the dropdown button, it would be nice if the dropdown button has the 'active' state when any of the links it contains is active, so that it can be styled in a way that is recognized by users, so that the navbar always shows "where you are".

> Just create a component in the same location and name. here it would be `app/components/bs-dropdown.js`. Inside of it you can import the original to extend from it: `import DropdownComponent from 'ember-bootstrap/components/bs-dropdown';`

Thank you!

**Comment by jelhan** [comment]
I don't think this is supported in Bootstrap. I'm going to close this issue. If I'm wrong and it is supported, please leave a comment. I'm happy to reopen in this case.
