### ISSUE TITLE
Prevent requiring ember-popper if not needed

### ISSUE THREAD

**Issue by simonihmig** [ember-bootstrap/ember-bootstrap#656]
Find a way to prevent `ember-popper` being added to the consuming app if not needed, e.g. if the component whitelist does not include one of bs-tooltip, bs-popover or bs-dropdown.

**Comment by donaldwasserman** [comment]
@simonihmig - how would I write a test for this?

**Comment by simonihmig** [comment]
@donaldwasserman sorry for my missing response here, somehow I missed the notification...

> how would I write a test for this?

Hm, good question. I have a test for the `whitelist`/`blacklist` functionality here: https://github.com/kaliber5/ember-bootstrap/blob/master/fastboot-tests/treeshake-test.js

It's not really related to FastBoot, but the test infrastructure (based on https://github.com/kaliber5/ember-fastboot-addon-tests) allows to test the addon in a "virtual app" (not `/tests/dummy`), so you can add custom fixtures that override the default app files and test results of the build process. Here there's a custom `ember-cli-build.js` (https://github.com/kaliber5/ember-bootstrap/blob/master/fastboot-tests/fixtures/treeshake/ember-cli-build.js), that has a whitelisted component. 

You could add a test rendering `{{#ember-popper}}` and asserting that it does *not* render. You could even make a request for `vendor.js` and search for something part of `popper.js` to make sure it is not included.

If you have something, just create a WIP PR, and we can try to add some tests...

**Comment by jelhan** [comment]
Embroider strict mode will give this out of the box. I feel we should not invest time anymore on supporting treeshaking in pre-Embroider world.
