### ISSUE TITLE
Add option to disable scrolling modals into view

### ISSUE THREAD

**Issue by bryanhickerson** [ember-bootstrap/ember-bootstrap#937]
We have added some of our modals rendered in place into our style guide, but having modals scroll automatically into view on render is a little problematic in this use case. Essentially the last modal in the view wins and is the initial scroll position even though it's not desired. This also makes snapshot testing of this view problematic because we end up with timing issues where the snapshot may be inconsistent depending on how quickly the modal scrolled fully into view.

It seems like we could change
https://github.com/kaliber5/ember-bootstrap/blob/2abc7de9edbf1df0f7a60ea38fc35076b4744e02/addon/components/base/bs-modal.js#L477
to be guarded by an option:
```
if (this.get('scrollIntoView') {
  modalEl.scrollTop = 0;
}
```

I'm happy to collaborate on this change, but I wanted to confirm that there was appetite for this change before opening a PR.

**Comment by simonihmig** [comment]
@bryanhickerson thanks for the suggestion, I think that would make sense! PR is certainly welcome! :wink:
